backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/apply/index.md"
        label: "Apply"
        name: "apply"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "join-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/vision/index.md"
        label: "Vision"
        name: "vision"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/testimonials/index.md"
        label: "Testimonials"
        name: "testimonial"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "testimonial"}
          - {label: Name, name: name, widget: string}
          - {label: Company, name: company, widget: string}
          - {label: Title, name: title, widget: string}
          - {label: URL, name: url, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Testimonial, name: testimonial, widget: string}
      - file: "src/pages/sponsors/index.md"
        label: "sponsors"
        name: "sponsors"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "testimonial"}
          - {label: Company, name: company, widget: string}
          - {label: URL, name: url, widget: string}
          - {label: Image, name: image, widget: image}
          